### ISSUE TITLE
Inquiry About Dataset Release Timeline

### ISSUE THREAD

**Issue by LeeKLTW** [MTU-Bench-Team/MTU-Bench#2]
Thank you for sharing the excellent paper. Is there an estimated timeline for releasing the dataset?

**Comment by NielsRogge** [comment]
Subscribing to this thread, would be great to make it available on HF, here's a guide: https://huggingface.co/docs/datasets/loading.

After uploaded, the dataset could be linked to the paper page: https://huggingface.co/papers/2410.11710

**Comment by Yupei-Wang** [comment]
> Subscribing to this thread, would be great to make it available on HF, here's a guide: https://huggingface.co/docs/datasets/loading.
> 
> After uploaded, the dataset could be linked to the paper page: https://huggingface.co/papers/2410.11710

Thank you for your suggestion! We have uploaded the dataset to HF. You can find it at the following link: https://huggingface.co/datasets/wpei/MTU-Bench

**Comment by Yupei-Wang** [comment]
> Thank you for sharing the excellent paper. Is there an estimated timeline for releasing the dataset?

Thank you for your interest in our work! We have already uploaded the evaluation dataset for MTU-Bench. You can access it in this repository or on Hugging Face:
https://huggingface.co/datasets/wpei/MTU-Bench
Regarding MTU-Instruct, we are currently in the process of organizing it and plan to release it in the future. Stay tuned for updates!

**Comment by NielsRogge** [comment]
Thanks a lot for publishing the dataset on the hub!

**Comment by LeeKLTW** [comment]
> Thank you for your interest in our work! We have already uploaded the evaluation dataset for MTU-Bench. You can access it in this repository or on Hugging Face: https://huggingface.co/datasets/wpei/MTU-Bench Regarding MTU-Instruct, we are currently in the process of organizing it and plan to release it in the future. Stay tuned for updates!

Thank you for the update. I am closing this issue since the dataset at https://huggingface.co/datasets/wpei/MTU-Bench is now accessible. I will stay tuned for future updates as well!
